---

- name: Add tailscale gpg key
  apt_key:
    url: https://pkgs.tailscale.com/stable/debian/buster.gpg 
    state: present
    
- name: Add tailscale repo
  apt_repository:
      repo: deb https://pkgs.tailscale.com/stable/debian buster main
      state: present
      update_cache: yes

- name: Install tailscale
  apt:
    name: tailscale
