---

- name: Run apt upgrade
  apt:
    upgrade: dist
    update_cache: yes
  become: yes

- name: Install essential pkgs
  apt:
    pkg:
      - vim
      - htop
      - git
      - hddtemp
      - ufw
    state: latest
  become: yes
