---

- hosts: all
  remote_user: root
  become: yes
  collections: 
    - devsec.hardening

  vars:
    sysctl_overwrite:
      # for docker support
      net.ipv4.ip_forward: 1
  vars_files:
    - ../vars.yml
  vars_prompt:
    - name: password
      prompt: "Enter your password: "
      private: yes

  roles:
    - os_hardening
    - ssh_hardening
    - utils
    - docker